name: Build and Deploy Jekyll Sites

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # Checkout submodules

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4 # Adjust to your required Ruby version
          bundler-cache: true # Cache gems based on root Gemfile.lock

      # --- Build os-study Site into a temporary directory ---
      - name: Build os-study Site
        run: |
          cd os-study
          # Build using submodule's config, setting baseurl, outputting to a temp dir at the root
          # This build should resolve includes relative to os-study/_includes
          bundle exec jekyll build --config _config.yml --baseurl /os-study -d ../_site_os_study --lsi
          cd ..
        env:
          JEKYLL_ENV: production

      # --- Build Main Site into the final _site directory ---
      - name: Build Main Site
        run: |
          # Build the main site into ./_site
          bundle exec jekyll build -d ./_site --lsi
        env:
          JEKYLL_ENV: production

      # --- Combine Build Artifacts ---
      - name: Combine Build Artifacts
        run: |
          # Ensure the target subdirectory exists in the main site output
          mkdir -p ./_site/os-study
          # Copy the built os-study site from the temp dir into the main site output
          cp -r ./_site_os_study/* ./_site/os-study/
          # Optional: Remove the temporary directory
          rm -rf ./_site_os_study

      # --- Configure and Upload ---
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the combined site from ./_site
          path: ./_site

      # --- Deploy ---
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4